define({
  "_widgetLabel": "Koordinaat",
  "hintMessage": "Klikkige koordinaatide hankimiseks kaardile",
  "defaultLabel": "Vaikimisi",
  "realtimeLabel": "Koordinaatide hankimiseks liigutage kursorit",
  "computing": "Arvutamine...",
  "latitudeLabel": "Laiuskraad",
  "longitudeLabel": "Pikkuskraad",
  "loading": "laadimine...",
  "enableClick": "Klikkige, et lubada klikkimise kaudu kaardilt koordinaate hankida",
  "disableClick": "Klikkige, et keelata klikkimise kaudu kaardilt koordinaate hankida",
  "Default": "Vaikimisi",
  "Inches": "Tolli",
  "Foot": "Jalga",
  "Yards": "Jardi",
  "Miles": "Miili",
  "Nautical_Miles": "Meremiili",
  "Millimeters": "Millimeetrit",
  "Centimeters": "Sentimeetrit",
  "Meter": "Meetrit",
  "Kilometers": "Kilomeetrit",
  "Decimeters": "Detsimeetrit",
  "Decimal_Degrees": "Kraadi",
  "Degree_Minutes_Seconds": "Kraadid minutid sekundid",
  "MGRS": "MGRS",
  "USNG": "USNG",
  "EYE_ALT": "vaate kõrgus",
  "ELEV": "kõrgus"
});