define({
  "sourceSetting": "Nastavení zdroje vyhledávání",
  "instruction": "Přidejte služby geokódování nebo vrstvy prvků a nakonfigurujte je jako zdroje vyhledávání. Tyto zadané zdroje budou určovat, co je možné vyhledávat v rámci pole pro hledání.",
  "add": "Přidat zdroj vyhledávání",
  "addGeocoder": "Přidat geokodér",
  "geocoder": "Geokodér",
  "setLayerSource": "Nastavit zdroj vrstvy",
  "setGeocoderURL": "Nastavit adresu URL geokodéru",
  "searchableLayer": "Vrstva prvků",
  "name": "Název",
  "countryCode": "Kódy země nebo oblasti",
  "countryCodeEg": "např. ",
  "countryCodeHint": "Pokud toto pole ponecháte prázdné, prohledají se všechny země a oblasti",
  "generalSetting": "Obecná nastavení",
  "allPlaceholder": "Zástupný text pro vyhledávání všech výsledků: ",
  "showInfoWindowOnSelect": "Zobrazit vyskakovací okno pro nalezený prvek nebo umístění",
  "searchInCurrentMapExtent": "Vyhledávat pouze v aktuálním rozsahu mapy",
  "zoomScale": "Měřítko přiblížení",
  "locatorUrl": "URL geokodéru",
  "locatorName": "Název geokodéru",
  "locatorExample": "Příklad",
  "locatorWarning": "Tato verze služby geokódování není podporována. Tento widget podporuje službu geokódování verze 10.0 a novější.",
  "locatorTips": "Návrhy nejsou k dispozici, protože služba geokódování nepodporuje funkcionalitu návrhů.",
  "layerSource": "Zdroj vrstvy",
  "searchLayerTips": "Návrhy nejsou k dispozici, protože služba Feature Service nepodporuje funkcionalitu stránkování.",
  "placeholder": "Zástupný text",
  "searchFields": "Prohledávaná pole",
  "displayField": "Zobrazované pole",
  "exactMatch": "Přesná shoda",
  "maxSuggestions": "Maximální počet návrhů",
  "maxResults": "Maximální počet výsledků",
  "setSearchFields": "Nastavit prohledávaná pole",
  "set": "Nastavit",
  "fieldSearchable": "prohledávatelné",
  "fieldName": "Název",
  "fieldAlias": "Alternativní jméno",
  "ok": "OK",
  "cancel": "Storno",
  "invalidUrlTip": "Adresa URL ${URL} je neplatná nebo nepřístupná.",
  "instruction2": "Přidejte služby geokódování a nakonfigurujte je jako zdroje vyhledávání. Tyto zadané zdroje budou určovat, co je možné vyhledávat v rámci vyhledávacího pole."
});