define({
  "_widgetLabel": "좌표",
  "hintMessage": "좌표를 가져오려면 맵 클릭",
  "defaultLabel": "기본",
  "realtimeLabel": "좌표를 가져오려면 마우스를 이동하세요.",
  "computing": "계산 중...",
  "latitudeLabel": "위도",
  "longitudeLabel": "경도",
  "loading": "불러오는 중...",
  "enableClick": "맵을 클릭하여 좌표 가져오기를 활성화하려면 클릭",
  "disableClick": "맵을 클릭하여 좌표 가져오기를 비활성화하려면 클릭",
  "Default": "기본",
  "Inches": "Inches",
  "Foot": "Feet",
  "Yards": "Yards",
  "Miles": "Miles",
  "Nautical_Miles": "해리",
  "Millimeters": "Millimeters",
  "Centimeters": "Centimeters",
  "Meter": "Meters",
  "Kilometers": "Kilometers",
  "Decimeters": "Decimeters",
  "Decimal_Degrees": "도",
  "Degree_Minutes_Seconds": "도-분-초",
  "MGRS": "MGRS",
  "USNG": "USNG",
  "EYE_ALT": "시야 고도",
  "ELEV": "고도"
});