define({
  "sourceSetting": "Pengaturan sumber pencarian",
  "instruction": "Tambah dan konfigurasikan layanan geocode atau layer fitur sebagai sumber pencarian. Sumber yang ditentukan ini menentukan apa yang dapat dicari dalam kotak pencarian.",
  "add": "Tambahkan sumber pencarian",
  "addGeocoder": "Tambahkan geocoder",
  "geocoder": "Geocoder",
  "setLayerSource": "Atur sumber layer",
  "setGeocoderURL": "Atur URL geocoder",
  "searchableLayer": "Feature layer",
  "name": "Nama",
  "countryCode": "Kode negara atau wilayah",
  "countryCodeEg": "mis. ",
  "countryCodeHint": "Membiarkan nilai ini kosong berarti akan mencari semua negara dan wilayah",
  "generalSetting": "Pengaturan umum",
  "allPlaceholder": "Tempat placehoder untuk mencari semua: ",
  "showInfoWindowOnSelect": "Tampilkan pop-up untuk fitur atau lokasi yang ditemukan",
  "searchInCurrentMapExtent": "Cari hanya dalam jangkauan peta saat ini",
  "zoomScale": "Skala zoom",
  "locatorUrl": "URL Geocoder",
  "locatorName": "Nama geocoder",
  "locatorExample": "Contoh",
  "locatorWarning": "Versi geocode service ini tidak didukung. Widget mendukung geocode service versi 10.0 dan lebih tinggi.",
  "locatorTips": "Saran tidak tersedia karena geocoding service tidak mendukung kapabilitas saran.",
  "layerSource": "Sumber layer",
  "searchLayerTips": "Saran tidak tersedia karena feature service tidak mendukung kemampuan penomoran halaman.",
  "placeholder": "Teks placeholder",
  "searchFields": "Kolom pencarian",
  "displayField": "Kolom tampilan",
  "exactMatch": "Persis",
  "maxSuggestions": "Saran maksimum",
  "maxResults": "Hasil maksimum",
  "setSearchFields": "Atur kolom pencarian",
  "set": "Atur",
  "fieldSearchable": "dapat dicari",
  "fieldName": "Nama",
  "fieldAlias": "Alias",
  "ok": "Ya",
  "cancel": "Batal",
  "invalidUrlTip": "URL ${URL} tidak valid atau tidak dapat diakses.",
  "instruction2": "Tambah dan konfigurasikan geocode service sebagai sumber pencarian. Sumber yang ditentukan ini menentukan apa yang dapat dicari dalam kotak pencarian."
});