define({
  "_widgetLabel": "Συντεταγμένες",
  "hintMessage": "Κάντε κλικ στον χάρτη για να λάβετε τις συντεταγμένες",
  "defaultLabel": "Προεπιλογή",
  "realtimeLabel": "Μετακινήστε το ποντίκι για να λάβετε τις συντεταγμένες",
  "computing": "Υπολογισμός...",
  "latitudeLabel": "Γεωγραφικό πλάτος",
  "longitudeLabel": "Γεωγραφικό μήκος",
  "loading": "φόρτωση...",
  "enableClick": "Κάντε κλικ για να ενεργοποιήσετε την επιλογή συντεταγμένων με κλικ στο χάρτη",
  "disableClick": "Κάντε κλικ για να απενεργοποιήσετε την επιλογή συντεταγμένων με κλικ στο χάρτη",
  "Default": "Προεπιλογή",
  "Inches": "Ίντσες",
  "Foot": "Πόδια",
  "Yards": "Γιάρδες",
  "Miles": "Μίλια",
  "Nautical_Miles": "Ναυτικά μίλια",
  "Millimeters": "Χιλιοστά",
  "Centimeters": "Εκατοστά",
  "Meter": "Μέτρα",
  "Kilometers": "Χιλιόμετρα",
  "Decimeters": "Δεκατόμετρα",
  "Decimal_Degrees": "Μοίρες",
  "Degree_Minutes_Seconds": "Μοίρες λεπτά δευτερόλεπτα",
  "MGRS": "MGRS",
  "USNG": "USNG",
  "EYE_ALT": "επίπεδο ματιών",
  "ELEV": "κλίση"
});