define({
  "_widgetLabel": "Koordinaatti",
  "hintMessage": "Nouda koordinaatit napsauttamalla karttaa",
  "defaultLabel": "Oletus",
  "realtimeLabel": "Nouda koordinaatit siirtämällä hiirtä",
  "computing": "Lasketaan...",
  "latitudeLabel": "Leveysaste",
  "longitudeLabel": "Pituusaste",
  "loading": "ladataan ...",
  "enableClick": "Ota napsauttamalla käyttöön koordinaattien nouto karttaa napsauttamalla",
  "disableClick": "Poista napsauttamalla käytöstä koordinaattien nouto karttaa napsauttamalla",
  "Default": "Oletus",
  "Inches": "Tuumaa",
  "Foot": "Jalkaa",
  "Yards": "Jaardia",
  "Miles": "Mailia",
  "Nautical_Miles": "Meripeninkulmaa",
  "Millimeters": "Millimetriä",
  "Centimeters": "Senttimetriä",
  "Meter": "Metriä",
  "Kilometers": "Kilometriä",
  "Decimeters": "Desimetriä",
  "Decimal_Degrees": "Astetta",
  "Degree_Minutes_Seconds": "Astetta minuuttia sekuntia",
  "MGRS": "MGRS",
  "USNG": "USNG",
  "EYE_ALT": "katselutaso",
  "ELEV": "korkeus"
});