define({
  "id": "Tunnus",
  "state": "Oletusarvon mukaan koordinaatit näytetään nykyisen kartan koordinaattijärjestelmässä. Jos haluat noutaa koordinaatit toisesta koordinaattijärjestelmästä, sinun on lisättävä ne ja määritettävä asianmukaiset transformaatiot.",
  "outputUnit": "Tulosyksikkö",
  "wkid": "Tulosaineiston WKID",
  "label": "Tulosaineiston koordinaattijärjestelmän nimi",
  "transformationWkid": "Transformaatio WKID",
  "transformationLabel": "Muunnon tunnusteksti",
  "transformForward": "Muunna eteenpäin",
  "actions": "Toimet",
  "warning": "Anna kelvollinen koordinaattijärjestelmän WKID!",
  "tfWarning": "Anna kelvollinen datumin transformaatio WKID!",
  "spinnerLabel": "Pyöristä koordinaatit: ",
  "eyeDecimalLabel": "Pyöristä katselutaso arvoon: ",
  "decimalPlace": "desimaalit",
  "separator": "Näytä tuhaterottimet",
  "getVersionError": "Geometriapalvelun versiotietoja ei voi noutaa",
  "add": "Lisää tulosaineiston koordinaattijärjestelmä",
  "edit": "Muokkaa koordinaattijärjestelmää",
  "output": "Tulosaineiston koordinaattijärjestelmä",
  "cName": "Koordinaattijärjestelmän nimi",
  "units": "Näytä yksiköt: ",
  "datum": "Datumimuunnos",
  "tName": "Transformaation nimi",
  "tWKIDPlaceHolder": "Transformaation WKID",
  "forward": "Käytä transformaatiota eteenpäin",
  "ok": "OK",
  "cancel": "Peruuta",
  "olderVersion": "Geometriapalvelu ei tue muuntotoimintoa",
  "REPEATING_ERROR": " Koordinaattijärjestelmä on syöteluettelossa.",
  "Default": "Oletus",
  "Inches": "Tuumaa",
  "Foot": "Jalkaa",
  "Yards": "Jaardia",
  "Miles": "Mailia",
  "Nautical_Miles": "Meripeninkulmaa",
  "Millimeters": "Millimetriä",
  "Centimeters": "Senttimetriä",
  "Meter": "Metriä",
  "Kilometers": "Kilometriä",
  "Decimeters": "Desimetriä",
  "Decimal_Degrees": "Desimaaliasteet",
  "Degree_Minutes_Seconds": "Astetta minuuttia sekuntia",
  "MGRS": "MGRS",
  "USNG": "USNG",
  "displayOrderLonLatTips": "Koordinaattien näyttöjärjestys:",
  "lonLatTips": "Pituusaste/leveysaste (X, Y)",
  "latLonTips": "Leveysaste/pituusaste(Y, X)"
});