define({
  "sourceSetting": "Nastavitve vira iskanja",
  "instruction": "Dodajte in konfigurirajte geokodirne storitve ali geoobjektne sloje kot vire iskanja. Ti viri določajo, kaj je mogoče iskati znotraj iskalnega polja.",
  "add": "Dodajte vir iskanja",
  "addGeocoder": "Dodajte geokodirnik",
  "geocoder": "Geokodirnik",
  "setLayerSource": "Nastavi vir sloja",
  "setGeocoderURL": "Nastavi URL geokodirnika",
  "searchableLayer": "Geoobjektni sloj",
  "name": "Ime",
  "countryCode": "Šifre države ali regije",
  "countryCodeEg": "npr. ",
  "countryCodeHint": "Če to vrednost pustite prazno, bo iskanje potekalo po vseh državah in regijah",
  "generalSetting": "Splošne nastavitve",
  "allPlaceholder": "Nadomestno besedilo za iskanje: ",
  "showInfoWindowOnSelect": "Pokaži pojavno okno za najdeni geoobjekt ali lokacijo",
  "searchInCurrentMapExtent": "Išči samo v trenutnem obsegu karte",
  "zoomScale": "Povečava merila",
  "locatorUrl": "URL geokodirnika",
  "locatorName": "Ime geokodirnika",
  "locatorExample": "Primer",
  "locatorWarning": "Ta različica geokodirnih storitev ni podprta. Pripomoček podpira različico geokodirne storitve 10.0 in novejšo.",
  "locatorTips": "Predlogi niso na voljo, ker geokodirna storitev ne podpira predlagane zmožnosti.",
  "layerSource": "Vir sloja",
  "searchLayerTips": "Predlogi niso na voljo, ker geoobjektna storitev ne podpira zmožnosti številčenja strani.",
  "placeholder": "Nadomestno besedilo",
  "searchFields": "Iskalna polja",
  "displayField": "Prikaži polje",
  "exactMatch": "Natančno ujemanje",
  "maxSuggestions": "Maksimalno predlogov",
  "maxResults": "Maksimalno rezultatov",
  "setSearchFields": "Nastavi iskalna polja",
  "set": "Nastavi",
  "fieldSearchable": "iskanje omogočeno",
  "fieldName": "Ime",
  "fieldAlias": "Vzdevek",
  "ok": "V redu",
  "cancel": "Prekliči",
  "invalidUrlTip": "URL ${URL} ni veljaven ali dostopen.",
  "instruction2": "Dodajte in konfigurirajte geokodirne storitve kot vire iskanja. Ti viri določajo, kaj je mogoče iskati znotraj iskalnega polja."
});