define({
  root: ({
    "sourceSetting": "Search source settings",
    "instruction": "Add and configure geocode services or feature layers as search sources. These specified sources determine what is searchable within the search box.",
    "add": "Add search source",
    "addGeocoder": "Add geocoder",
    "geocoder": "Geocoder",
    "setLayerSource": "Set layer source",
    "setGeocoderURL": "Set geocoder URL",
    "searchableLayer": "Feature layer",
    "name": "Name",
    "countryCode": "Country or region code(s)",
    "countryCodeEg": "e.g. ",
    "countryCodeHint": "Leaving this value blank will search all countries and regions",
    "generalSetting": "General settings",
    "allPlaceholder": "Placeholder text for searching all: ",
    "showInfoWindowOnSelect": "Show pop-up for the found feature or location",
    "searchInCurrentMapExtent": "Only search in current map extent",
    "zoomScale": "Zoom scale",
    "locatorUrl": "Geocoder URL",
    "locatorName": "Geocoder name",
    "locatorExample": "Example",
    "locatorWarning": "This version of geocoding service is not supported. The widget supports geocoding service 10.0 and above.",
    "locatorTips": "Suggestions are not available because the geocoding service doesn't support suggest capability.",
    "layerSource": "Layer source",
    "searchLayerTips": "Suggestions are not available because the feature service doesn't support pagination capability.",
    "placeholder": "Placeholder text",
    "searchFields": "Search fields",
    "displayField": "Display field",
    "exactMatch": "Exact match",
    "maxSuggestions": "Maximum suggestions",
    "maxResults": "Maximum results",
    "setSearchFields": "Set search fields",
    "set": "Set",
    "fieldSearchable": "searchable",
    "fieldName": "Name",
    "fieldAlias": "Alias",
    "ok": "OK",
    "cancel": "Cancel",
    "invalidUrlTip": "The URL ${URL} is invalid or inaccessible.",
    "instruction2": "Add and configure geocode services as search sources. These specified sources determine what is searchable within the search box.",

  }),
  "ar": 1,
  "bs": 1,
  "ca": 1,
  "cs": 1,
  "da": 1,
  "de": 1,
  "el": 1,
  "es": 1,
  "et": 1,
  "fi": 1,
  "fr": 1,
  "he": 1,
  "hi": 1,
  "hr": 1,
  "hu": 1,
  "it": 1,
  "id": 1,
  "ja": 1,
  "ko": 1,
  "lt": 1,
  "lv": 1,
  "nb": 1,
  "nl": 1,
  "pl": 1,
  "pt-br": 1,
  "pt-pt": 1,
  "ro": 1,
  "ru": 1,
  "sl": 1,
  "sr": 1,
  "sv": 1,
  "th": 1,
  "tr": 1,
  "vi": 1,
  "zh-cn": 1,
  "zh-hk": 1,
  "zh-tw": 1
});
