define({
  "_widgetLabel": "Koordinat",
  "hintMessage": "Klicka på kartan för att hämta koordinater",
  "defaultLabel": "Standard",
  "realtimeLabel": "Flytta musen för att hämta koordinater",
  "computing": "Beräknar ...",
  "latitudeLabel": "Latitud",
  "longitudeLabel": "Longitud",
  "loading": "läser in...",
  "enableClick": "Klicka om du vill aktivera att få koordinater genom att klicka på kartan",
  "disableClick": "Klicka om du vill inaktivera att få koordinater genom att klicka på kartan",
  "Default": "Standard",
  "Inches": "Tum",
  "Foot": "Fot",
  "Yards": "Yard",
  "Miles": "Mile",
  "Nautical_Miles": "Nautiska mil",
  "Millimeters": "Millimetrar",
  "Centimeters": "Centimeter",
  "Meter": "Meter",
  "Kilometers": "Kilometer",
  "Decimeters": "Decimeter",
  "Decimal_Degrees": "Grader",
  "Degree_Minutes_Seconds": "Grader minuter sekunder",
  "MGRS": "MGRS",
  "USNG": "USNG",
  "EYE_ALT": "eye alt",
  "ELEV": "elev"
});