define({
  "sourceSetting": "स्रोत सेटिंग खोजें",
  "instruction": "Geocode सेवाओं या फीचर लेयरों को खोज स्रोतों के रूप में जोड़ें और कॉन्फ़िगर करें। ये निर्दिष्ट स्रोत निर्धारित करते हैं कि खोज बॉक्स के भीतर क्या खोज योग्य है।",
  "add": "खोज स्रोत जोड़ें",
  "addGeocoder": "geocoder जोड़ें",
  "geocoder": "Geocoding",
  "setLayerSource": "लेयर स्रोत को सेट करें",
  "setGeocoderURL": "geocoder का URL सेट करें",
  "searchableLayer": "फ़ीचर लेयर",
  "name": "नाम",
  "countryCode": "देश या क्षेत्र कोड",
  "countryCodeEg": "जैसे ",
  "countryCodeHint": "इस मान को खाली छोड़ने से सभी देशों और क्षेत्रों की खोज होगी",
  "generalSetting": "सामान्य सेटिंग्स",
  "allPlaceholder": "सभी खोज के लिए प्लेसहोल्डर टेक्स्ट: ",
  "showInfoWindowOnSelect": "पाई गई फीचर या स्थान के लिए पॉप-अप दिखाएं",
  "searchInCurrentMapExtent": "केवल वर्तमान मानचित्र सीमा में खोज करता है",
  "zoomScale": "स्केल को ज़ूम करें",
  "locatorUrl": "जियोकोडर URL",
  "locatorName": "जियोकोडर का नाम",
  "locatorExample": "उदाहरण",
  "locatorWarning": "Geocoding सेवा का यह संस्करण समर्थित नहीं है। विजेट Geocoding सेवा 10.0 और ऊपर को समर्थन करता है।",
  "locatorTips": "सुझाव उपलब्ध नहीं हैं क्योंकि Geocoding सेवा सुझाव क्षमता का का समर्थन नहीं करता है।",
  "layerSource": "लेयर स्रोत को सेट करें",
  "searchLayerTips": "सुझाव उपलब्ध नहीं हैं क्योंकि सुविधा सेवा पृष्ठ अंकन क्षमता का समर्थन नहीं करती है।",
  "placeholder": "प्लेसहोल्डर टेक्स्ट",
  "searchFields": "फ़ील्ड खोजें",
  "displayField": "डिस्प्ले फील्ड्स",
  "exactMatch": "सटीक मिलान",
  "maxSuggestions": "अधिकतम सुझाव",
  "maxResults": "अधिकतम परिणाम",
  "setSearchFields": "खोज फ़ील्ड को सेट करें",
  "set": "सेट करें",
  "fieldSearchable": "खोज योग्य",
  "fieldName": "नाम",
  "fieldAlias": "उपनाम",
  "ok": "ठीक है",
  "cancel": "रद्द करें",
  "invalidUrlTip": "URL ${URL} अवैध या दुर्गम है।",
  "instruction2": "जियोकोडर सेवाओं या फीचर लेयरों को खोज स्रोतों के रूप में जोड़ें और कॉन्फ़िगर करें। ये निर्दिष्ट स्रोत निर्धारित करते हैं कि खोज बॉक्स के भीतर क्या खोजने योग्य है।"
});