define({
  "sourceSetting": "Configurações da fonte de pesquisa",
  "instruction": "Adicione e configure serviços de geocódigo ou camadas de feição como fontes de pesquisa. Estas fontes especificadas determinam o que é pesquisável dentro da caixa de pesquisa.",
  "add": "Adicionar fonte de pesquisa",
  "addGeocoder": "Adicionar geocodificador",
  "geocoder": "Geocodificador",
  "setLayerSource": "Configurar fonte da camada",
  "setGeocoderURL": "Configurar URL do geocodificador",
  "searchableLayer": "Camada de feição",
  "name": "Nome",
  "countryCode": "Códigos de região e país",
  "countryCodeEg": "por exemplo ",
  "countryCodeHint": "Deixar este valor em branco pesquisará todos os países e regiões",
  "generalSetting": "Configurações gerais",
  "allPlaceholder": "Texto de local reservado para pesquisar todos: ",
  "showInfoWindowOnSelect": "Mostrar pop-up do local ou feição localizada",
  "searchInCurrentMapExtent": "Somente pesquisar na extensão de mapa atual",
  "zoomScale": "Escala de zoom",
  "locatorUrl": "URL do Geocodificador",
  "locatorName": "Nome de geocodificador",
  "locatorExample": "Exemplo",
  "locatorWarning": "Esta versão do serviço de geocodificação não é suportado. O widget suporta serviço de geocodificação 10.0 e superior.",
  "locatorTips": "As sugestões não estão disponíveis, pois o serviço de geocodificação não suporta o recursos de sugestão.",
  "layerSource": "Fonte de camada",
  "searchLayerTips": "As sugestões não estão disponíveis, pois o serviço da feição não suporta o recursos de paginação.",
  "placeholder": "Texto reservado",
  "searchFields": "Procurar campos",
  "displayField": "Campo de visualização",
  "exactMatch": "Combinação exata",
  "maxSuggestions": "Máximo de sugestões",
  "maxResults": "Máximo de resultados",
  "setSearchFields": "Definir campos de pesquisa",
  "set": "Configurar",
  "fieldSearchable": "pesquisável",
  "fieldName": "Nome",
  "fieldAlias": "Nome Alternativo",
  "ok": "Ok",
  "cancel": "Cancelar",
  "invalidUrlTip": "A URL ${URL} é inválida ou inacessível.",
  "instruction2": "Adicione e configure serviços de geocódigo como fontes de pesquisa. Estas fontes especificadas determinam o que é pesquisável na caixa de pesquisa."
});