define({
  "_widgetLabel": "Souřadnice",
  "hintMessage": "Kliknutím na mapu získáte souřadnice.",
  "defaultLabel": "Výchozí",
  "realtimeLabel": "Souřadnice získáte pohybem myši po mapě.",
  "computing": "Probíhá výpočet…",
  "latitudeLabel": "Zeměpisná šířka",
  "longitudeLabel": "Zeměpisná délka",
  "loading": "nahrávání…",
  "enableClick": "Kliknutím povolíte získávání souřadnic pomocí kliku do mapy.",
  "disableClick": "Kliknutím zakážete získávání souřadnic pomocí kliku do mapy.",
  "Default": "Výchozí",
  "Inches": "Palce",
  "Foot": "Stopy",
  "Yards": "Yardy",
  "Miles": "Míle",
  "Nautical_Miles": "Námořní míle",
  "Millimeters": "Milimetry",
  "Centimeters": "Centimetry",
  "Meter": "Metry",
  "Kilometers": "Kilometry",
  "Decimeters": "Decimetry",
  "Decimal_Degrees": "stupně",
  "Degree_Minutes_Seconds": "Stupně minuty vteřiny",
  "MGRS": "Vojenská hlásná síť (MGRS)",
  "USNG": "USNG",
  "EYE_ALT": "výšková pol. pozorovatele",
  "ELEV": "nadm. v."
});