define({
  "sourceSetting": "Configuració de l'origen de la cerca",
  "instruction": "Afegiu i configureu serveis de geocodificació o capes d'entitats com a orígens de cerca. Aquests orígens especificats determinen què es pot cercar al quadre de cerca.",
  "add": "Afegeix un origen de cerca",
  "addGeocoder": "Afegeix un geocodificador",
  "geocoder": "Geocodificador",
  "setLayerSource": "Defineix l'origen de la capa",
  "setGeocoderURL": "Defineix la URL del geocodificador",
  "searchableLayer": "Capa d'entitats",
  "name": "Nom",
  "countryCode": "Codis de país o regió",
  "countryCodeEg": "per exemple, ",
  "countryCodeHint": "Si aquest valor es deixa en blanc, la cerca es farà en tots els països i regions",
  "generalSetting": "Configuració general",
  "allPlaceholder": "Text del marcador de posició per cercar-ho tot: ",
  "showInfoWindowOnSelect": "Mostra la finestra emergent de l'entitat o la ubicació trobada",
  "searchInCurrentMapExtent": "Cerca només a l'extensió de mapa actual",
  "zoomScale": "Escala de zoom",
  "locatorUrl": "URL del geocodificador",
  "locatorName": "Nom del geocodificador",
  "locatorExample": "Exemple",
  "locatorWarning": "Aquesta versió del servei de geocodificació no s'admet. El widget admet el servei de geocodificació 10.0 i versions posteriors.",
  "locatorTips": "Els suggeriments no estan disponibles perquè el servei de geocodificació no admet la funció de suggeriments.",
  "layerSource": "Origen de la capa",
  "searchLayerTips": "Els suggeriments no estan disponibles perquè el servei d'entitats no admet la funció de paginació.",
  "placeholder": "Text del marcador de posició",
  "searchFields": "Camps de cerca",
  "displayField": "Camp que es mostra",
  "exactMatch": "Coincidència exacta",
  "maxSuggestions": "Màxim de suggeriments",
  "maxResults": "Màxim de resultats",
  "setSearchFields": "Defineix els camps de cerca",
  "set": "Defineix",
  "fieldSearchable": "permet la cerca",
  "fieldName": "Nom",
  "fieldAlias": "Àlies",
  "ok": "D'acord",
  "cancel": "Cancel·la",
  "invalidUrlTip": "L'adreça URL ${URL} no és vàlida o no s'hi pot accedir.",
  "instruction2": "Afegiu i configureu serveis de geocodificació com a orígens de cerca. Aquests orígens especificats determinen què es pot cercar al quadre de cerca."
});