define({
  "_widgetLabel": "Współrzędne",
  "hintMessage": "Kliknij na mapie, aby pobrać współrzędne",
  "defaultLabel": "Domyślne",
  "realtimeLabel": "Przesuń kursor myszy, aby pobrać współrzędne",
  "computing": "Trwa obliczanie...",
  "latitudeLabel": "Szerokość geograficzna",
  "longitudeLabel": "Długość geograficzna",
  "loading": "trwa wczytywanie...",
  "enableClick": "Kliknij, aby włączyć klikanie na mapie w celu uzyskania współrzędnych",
  "disableClick": "Kliknij, aby wyłączyć klikanie na mapie w celu uzyskania współrzędnych",
  "Default": "Domyślne",
  "Inches": "Cale",
  "Foot": "Stopy",
  "Yards": "Jardy",
  "Miles": "Mile",
  "Nautical_Miles": "Mile morskie",
  "Millimeters": "Milimetry",
  "Centimeters": "Centymetry",
  "Meter": "Metry",
  "Kilometers": "Kilometry",
  "Decimeters": "Decymetry",
  "Decimal_Degrees": "Stopnie",
  "Degree_Minutes_Seconds": "Stopnie, minuty i sekundy",
  "MGRS": "MGRS",
  "USNG": "USNG",
  "EYE_ALT": "wys widzenia",
  "ELEV": "wys"
});